
name: Publish Python
description: "Publish Assets and Report"
inputs:
  version:
    description: "The published version"
    required: true
  product_name:
    description: "The name of the product"
    required: true
  aws_bucket_name:
    description: "The aws bucket name for uploads"
    required: true
  token:
    description: "The GitHub access token"
    required: true
  dry_run:
    description: "Whether this is a dry run"
    required: true

runs:
  using: composite
  steps:
    - name: Download all the dists
      uses: actions/download-artifact@v3
      with:
        name: all-dist-${{ github.run_id }}
        path: dist/
    - name: Create detached signature for dist files
      uses: ./.github/actions/gpg-sign
      with:
        filenames: dist/*
    - name: Move the signature files to a separate directory
      shell: bash
      run: |
        set -eux
        mkdir signatures
        mv dist/*.sig signatures
    - uses: mongodb-labs/drivers-github-tools/papertrail@main
      with:
        product_name: ${{ inputs.product_name }}
        release_version: ${{ inputs.version }}
        filenames: dist/*
        token: ${{ inputs.token }}
    - name: Run publish script
      shell: bash
      run: ${{ github.action_path }}/publish.sh
      env:
        GH_TOKEN: ${{ inputs.token }}
        VERSION: ${{ inputs.version }}
        PRODUCT_NAME: ${{ inputs.product_name }}
        DRY_RUN: ${{ inputs.dry_run }}
    # https://packaging.python.org/en/latest/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/#publishing-the-distribution-to-pypi
    # - name: Publish distribution 📦 to PyPI
    #   if: inputs.dry_run == 'false'
    #   uses: pypa/gh-action-pypi-publish@release/v1
