name: Tag Version
description: "Tag current version and push if not dry run"
inputs:
  version:
    description: "The tag version"
    required: true
  garasign_username:
    description: "The garasign username"
    required: true
  garasign_password:
    description: "The garasign password"
    required: true
  artifactory_username:
    description: "The artifactory username"
    required: true
  artifactory_password:
    description: "The artifactory password"
    required: true
  gpg_key_id:
    description: "The gpg key id"
    required: true
  dry_run:
    description: "Whether this is a dry run"
    required: true

runs:
  using: composite
  steps:
  - name: Set up Git Config
    shell: bash
    run: |
      # Use the GitHub Actions bot as the actor.
      git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
      git config user.name "github-actions[bot]"

      if [ -n "$(git status --porcelain)" ]; then
        echo "Uncommitted changes!"
        git status --porcelain
        exit 1
      fi

  - name: Tag the version
    uses: mongodb-labs/drivers-github-tools/garasign/git-sign@main
    with:
      command: git tag -a \"${{ inputs.version }}\" -m \"BUMP ${{ inputs.version }}\" -s --local-user=${{ inputs.gpg_key_id }}
      garasign_username: ${{ inputs.garasign_username }}
      garasign_password: ${{ inputs.garasign_password }}
      artifactory_username: ${{ inputs.artifactory_username }}
      artifactory_password: ${{ inputs.artifactory_password }}
      skip_setup: true

  - name: Verify the tag
    shell: bash
    run: |
      curl -O https://pgp.mongodb.com/python-driver.pub
      gpg --import python-driver.pub
      git verify-tag ${{inputs.version}}
      rm python-driver.pub

  - name: Push the tag to the source branch
    shell: bash
    run: |
      if [ ${{ inputs.dry_run }} != "true" ]; then
        git push origin --tags
      fi
