name: Build
on: [push, pull_request]

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  windows-msys2:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        msystem: [MINGW64, MINGW32, UCRT64, CLANG64]
    name: Build (${{ matrix.msystem }})
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: actions/checkout@v2
      - uses: msys2/setup-msys2@v2
        with:
          msystem: ${{ matrix.msystem }}
          update: true
          pacboy: cc:p python:p python-setuptools:p python-sphinx:p
      - name: Build
        run: CC=cc python setup.py build
      - name: Check
        run: |
          CC=cc python setup.py build_ext --inplace
          python -c "import winkerberos;print(winkerberos.__version__)"
  windows-msvc:
    runs-on: windows-latest
    name: Build MSVC
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9, "3.10"]
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Build
        run: python setup.py build
      - name: Check
        run: |
          python setup.py build_ext --inplace
          python -c "import winkerberos;print(winkerberos.__version__)"
