name: Python Wheels

on: [push, pull_request]

concurrency:
  group: release-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_newer_wheels:
    runs-on: windows-2019
    strategy:
      fail-fast: false
      matrix:
        buildplat: ["win_amd64", "win32"]
        python: ["cp35", "cp36", "cp37", "cp38", "cp39", "cp310"]
    steps:
      - uses: actions/checkout@v2
      - name: Build wheels
        uses: pypa/cibuildwheel@v2.4.0
        env:
          CIBW_BUILD: ${{ matrix.python }}-${{ matrix.buildplat }}
          CIBW_TEST_COMMAND: "python -c \"import winkerberos;print(winkerberos.__version__)\""

      - uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.python }}-${{ matrix.buildplat }}
          path: ./wheelhouse/*.whl

  build_older_wheels:
    runs-on: windows-2019
    strategy:
      fail-fast: false
      matrix:
        buildplat: ["win_amd64", "win32"]
        python: ["cp27", "cp35"]
    steps:
      - uses: actions/checkout@v2
      - name: "Install Visual C++ for Python 2.7"
        run: "choco install vcpython27 -f -y --source=\"'.;https://chocolatey.org/api/v1`'\""
      - name: Build wheels
        uses: pypa/cibuildwheel@v1.12.0
        env:
          CIBW_BUILD: ${{ matrix.python }}-${{ matrix.buildplat }}
          CIBW_TEST_COMMAND: "python -c \"import winkerberos;print(winkerberos.__version__)\""

      - uses: actions/upload-artifact@v3
        with:
          name: cp27-win_amd64
          path: ./wheelhouse/*.whl

  make_sdist:
    name: Make SDist
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build SDist
        run: |
          pip install build check-manifest
          check-manifest -v
          python -m build --sdist .
      - uses: actions/upload-artifact@v2
        with:
          name: "sdist"
          path: dist/*.tar.gz

  collect_wheels:
    runs-on: ubuntu-latest
    needs: [build_newer_wheels, build_older_wheels, make_sdist]
    name: Download Wheels
    steps:
      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v2
      - name: Flatten directory
        run: |
          find . -mindepth 2 -type f -exec mv {} . \;
          find . -type d -empty -delete
      - uses: actions/upload-artifact@v2
        with:
          name: all-dist
          path: "./*"
